#!/usr/bin/env python

import numpy as np

# DES terms
DESAstrometry = 0.001     
DESNonLinearity = 0.001
DESPhotometricZeroPointing = 0.002
DESPhotometricBias = 0.003
DESUniformity = 0.0066 / np.sqrt(3.)

DESFilterList = ['g', 'r', 'i', 'z']
DESABUncertainty = {'g': 0.002, 'r': 0.002, 'i': 0.001, 'z': 0.005} # mag
DESFilterUncertainty = {'g': 0.6, 'r': 0.6, 'i': 0.6, 'z': 0.6} # nm
DESCentralWavelengths = {'g': 481, 'r': 644, 'i': 781, 'z': 913} # nm

baseUncertainty = DESAstrometry ** 2 + \
                    DESNonLinearity ** 2 + \
                    DESPhotometricZeroPointing ** 2 + \
                    DESPhotometricBias ** 2 + \
                    DESUniformity ** 2

DESZPUncertainty = {f: round(np.sqrt((DESABUncertainty[f] ** 2.) + (baseUncertainty ** 2.)), 3) for f in DESFilterList}
preamble = "# Generated by generate_DES.py\nFilter, σZP (mag),  σFilter (nm),   CW (nm)"
for filt in DESFilterList:
    preamble += f"\n{filt}, {DESZPUncertainty[filt]}, {DESFilterUncertainty[filt]}, {DESCentralWavelengths[filt]}"
with open("DES", 'w') as f:
    f.write(preamble)

